name: Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Runs the E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2

      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24.11.1"

      - name: Install dependencies
        run: npm install

      - name: Generate prisma client
        run: npm run db:generate

      - name: Install PlayWright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm run test:e2e
        env:
          DATABASE_URL: ${{secrets.TEST_DATABASE_URL}}

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-report
          path: tests-result-report
          retention-days: 30

# We can also add a lint check, formatting check, type check & step to upload the tests result to some place
# in the GitHub repo.
